FOLDER = r"/home/brocolimanx/Desktop/appdemo 2/appdemo"

WIDTH = 2796
HEIGHT = 1290
ASPECT = 16/9
FPS = 22
MAX_FRAME_TIME = 0.03
EYE_DISPLACEMENT = 0.1
BOXHEIGHT = 720
XBOX_LISTEN_DELAY = 0.1
MENU_CURR_HOVER = "#b0b0b0"
MENU_HOVER = "#d0d0d0"
MENU_DEFAULT = "white"

XBOX_A = 0
XBOX_B = 1
XBOX_X = 2
XBOX_Y = 3
XBOX_LB = 4
XBOX_RB = 5
XBOX_DUP = (0, 1)
XBOX_DDOWN = (0, -1)
XBOX_DLEFT = (-1, 0)
XBOX_DRIGHT = (1, 0)
XBOX_AXIS_LX = 0
XBOX_AXIS_LY = 1
XBOX_AXIS_RX = 2
XBOX_AXIS_RY = 3